# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Hy7Q292z7BnPke2Pgs8rMxUyFKu-hHwW
"""

import random

def inicio():
  print("El juego consiste en escoger un número entre 1 y 10, y luego adivinar si otro valor al azar será mayor o menor que el seleccionado")
  x = int(input("Ingresa un 1 si estas listo para jugar!: "))
  if (x != 1):
    print("Que fome, vamos a jugar igual!")